### ISSUE TITLE
Failing with cannot use a CodeBuild curated image with imagePullCredentialsType SERVICE_ROLE

### ISSUE THREAD

**Issue by siboulet** [aws/aws-codebuild-docker-images#163]
We've been using CodeBuild to build Docker images for a little while. Over the weekend all our Docker builds using the docker image started to fail with "cannot use a CodeBuild curated image with imagePullCredentialsType SERVICE_ROLE".

We're using the `aws/codebuild/docker:17.09.0` image as outlined in https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html.

I tried recreating the project in the CodeBuild console and getting the same error when saving the project: "Invalid input: cannot use a CodeBuild curated image with imagePullCredentialsType SERVICE_ROLE".

![codebuild aws developer tools](https://user-images.githubusercontent.com/2367545/51932330-f4ddfc00-23cc-11e9-9322-9c1dd501f21f.png)

![screenshot_2019-01-29_13-48-16](https://user-images.githubusercontent.com/2367545/51932165-90bb3800-23cc-11e9-97bf-69a4ea2355fe.png)

**Comment by siboulet** [comment]
Oh, wait a minute. I'm 100% sure the above is how I initially configured our project. But I just tried going to the "Managed Image" list and picking Docker from there and it seems to work now.

![screenshot_2019-01-29_14-14-31](https://user-images.githubusercontent.com/2367545/51934051-b8ac9a80-23d0-11e9-9803-1de1c7842dd1.png)

Closing.

**Comment by leobaran-aws** [comment]
CodeBuild now supports pulling images with two different sets of credentials: your project's service role (new) or CodeBuild's own service credentials (default option). When you select `Custom image` in the console, it automatically selects the service role credentials option. Since we don't support pulling CodeBuild curated images with service role credentials, the error appeared when trying to update your project. 

I'll see if we can add an exception to this logic to prevent further confusion. Thanks for letting us know about this issue.

**Comment by ookangzheng** [comment]
Just now I also got this error 
`cannot use a CodeBuild curated image with imagePullCredentialsType SERVICE_ROLE`
I try to switch between from `DockerRegistry` to Codebuild curated image

```javascript
environment: {
          // buildImage: LinuxBuildImage.fromDockerRegistry('docker:dind')
          buildImage: LinuxBuildImage.STANDARD_4_0
        }
```

**Comment by leoherran-aws** [comment]
CodeBuild supports pulling images with two different sets of credentials: your project's service role or CodeBuild's own service credentials. We don't support pulling CodeBuild curated images with service role credentials, so you'll need to update `imagePullCredentialsType` from `SERVICE_ROLE` to `CODEBUILD` in order to configure your project with a CodeBuild image.

**Comment by DVMVCGCG** [comment]
There seems to be a CDK bug where the `Environment.ImagePullCredentialType` is not emitted in the CF template even when setting the `buildImage` to a CodeBuild provided image such as in the example provided by @ookangzheng above. I had to use a raw property override to get rid of the `cannot use a CodeBuild curated image with imagePullCredentialsType SERVICE_ROLE` error.

```ts
const cfnProject = codeBuildProject.node.findChild('Resource') as codebuild.CfnProject
cfnProject.addPropertyOverride(
    'Environment.ImagePullCredentialsType',
    'CODEBUILD'
)
```

**Comment by ggorge-etiqa** [comment]
@leoherran-aws you should fix the AWS console too as it seems there is no way to select  the `ImagePullCredentialsType`

**Comment by awsluja** [comment]
Is there no way to mix curated images with non-curated images?
We use a custom linux image, but need to also run windows tests.
So we use SERVICE_ROLE for the linux image, but need to use CODEBUILD for the windows curated image. Is this not possible? Can this flag be made at the individual build level, instead of the project level?

**Comment by awsluja** [comment]
> Is there no way to mix curated images with non-curated images? We use a custom linux image, but need to also run windows tests. So we use SERVICE_ROLE for the linux image, but need to use CODEBUILD for the windows curated image. Is this not possible? Can this flag be made at the individual build level, instead of the project level?

we are using CDK and found a workaround by using the custom image as our default image when setting up the project

```
const project = new codebuild.Project(this, "projecid", {
      projectName: "projectname",
      badge: true,
      source: gitHubSource,
      buildSpec: codebuild.BuildSpec.fromSourceFilename(
        "codebuild_specs/base.yml"
      ),
      environment: {
        buildImage: customImage,
```
and then we override the image pull credentials to CODEBUILD role in the CDK project, so that we can use curated images provided by AWS CodeBuild
   
```
const cfnProject = project.node.findChild('Resource') as codebuild.CfnProject;
cfnProject.addPropertyOverride('Environment.ImagePullCredentialsType','CODEBUILD');
```
and also to compensate for using the CODEBUILD role, we need to grant permissions in ECR to allow the CODEBUILD role to pull our custom images
```
ecrRepository.addToResourcePolicy(new PolicyStatement({
      sid: "AllowAccess",
      effect: Effect.ALLOW,
      principals: [
        new ServicePrincipal('codebuild.amazonaws.com')
      ],
      actions: [
        "ecr:BatchCheckLayerAvailability",
        "ecr:BatchGetImage",
        "ecr:GetDownloadUrlForLayer"
      ]
    }))
```
