### ISSUE TITLE
Support for .NET Core 3.1

### ISSUE THREAD

**Issue by broder-peters-k24** [aws/aws-codebuild-docker-images#297]
In an already closed issue, there has been a statement that the image for net core 3.1 will delay. Are there any updates? How long will it take?

> Thanks for checking in on the status. Devs ran into some regression and had to rollback the update that was supposed to happen yesterday. Team is working on fixing this. Apologies for the delay.

_Originally posted by @subinataws in https://github.com/aws/aws-codebuild-docker-images/issues/277#issuecomment-577433149_

**Comment by subinataws** [comment]
Apologies for the delay in getting this version out. The longer than expected delay is due to a [rollback that we had to do in order to prevent long provisioning time](https://github.com/aws/aws-codebuild-docker-images/issues/296) for customers using an earlier version of CodeBuild provided image. Team is working on optimizing some layers to free up space needed to get 3.1 shipped (along with a few other runtime updates). Let's continue to track this in one place @ https://github.com/aws/aws-codebuild-docker-images/issues/277. Resolving this issue.
