### ISSUE TITLE
Buildspec not found on Windows

### ISSUE THREAD

**Issue by hm2602** [aws/aws-codebuild-docker-images#320]
Hello, I am running on Windows and cannot get the Codebuild agent to pick up my buildspec.yml file. I have tried it both at the root and in other locations in conjunction with the -b flag, but the error below is what I get every time.
`agent_1  | [Container] 2020/03/19 22:02:41 Phase complete: DOWNLOAD_SOURCE State: FAILED`
`agent_1  | [Container] 2020/03/19 22:02:41 Phase context status code: YAML_FILE_ERROR Message: YAML file does not exist`
`agent_1  | [Container] 2020/03/19 22:02:41 Runtime error (*clienterr.PhaseContextError: YAML file does not exist)`
`agent-resources_build_1 exited with code 11`

Full output
![3 19 20](https://user-images.githubusercontent.com/10245523/77119616-71320500-69fc-11ea-89ca-a74d36f79b50.PNG)
![3 19 20 2](https://user-images.githubusercontent.com/10245523/77119612-6f684180-69fc-11ea-90c2-c043d6f8dd23.PNG)

**Comment by awszhen** [comment]
Hi @hm2602 , could you please check whether you have shared your `C drive` to `Docker`? Thanks.

**Comment by hm2602** [comment]
yeah it is shared

**Comment by awszhen** [comment]
@hm2602 , I can not reproduce the issue you mentioned. This is my configuration.

![Capture](https://user-images.githubusercontent.com/32624806/79276118-46e93100-7e5c-11ea-8ff4-7825fe64cddf.PNG)

Please refer to https://github.com/aws/aws-codebuild-docker-images/issues/145.

**Comment by subinataws** [comment]
When this was previously reported by another customer in the linked ticket above, it was a transient issue which resolved itself with a restart of docker. Could you please try that on your end? We can't reproduce this on our end on Windows and without being able to repro, we aren't able to address the issue you are running into.

**Comment by butlnor** [comment]
Well I have exactly the same issue. Using WSL2 on Win10 for the Docker Desktop, so the drives are automatically shared with Docker. I get the exactly same error message. Restarting the docker didn't help. 

After the (internal) agent container is stopped because of an error, I can manually start it back. If I looked into the directory, that is supposed to be a mount of the source directory on the host machine, is empty.

The funny thing is that when I inspect the container and look at the mounts, I see the windows drive mounted as "/c/something". But if I use some unrelated docker image and run it with "-v" param, it does mount properly, as from inside the container, I can list the files from the host machine. The difference is, that here, when inspecting the container, I see the drive mounted as "//c/something". Notice the **double** slash at the beginning.

I guess the issue might be connected as the agent container not using the double leading slashes?

**Comment by jshep96** [comment]
I also have the same issue. Running docker for Windows on WSL2 so all drives are automatically shared.

Exactly the same error message.

**Comment by zzareyan-amp** [comment]
Can confirm of having this issue...
