### ISSUE TITLE
Add support for Local Cache in local_builds

### ISSUE THREAD

**Issue by larstobi** [aws/aws-codebuild-docker-images#344]
Although S3 backed cache will not be supported (#99), maybe we can have support for Local Cache in `local_builds/codebuild_build.sh`?

* https://aws.amazon.com/about-aws/whats-new/2019/02/aws-codebuild-now-supports-local-caching/
* https://docs.aws.amazon.com/codebuild/latest/userguide/build-caching.html#caching-local
* https://aws.amazon.com/blogs/devops/improve-build-performance-and-save-time-using-local-caching-in-aws-codebuild/

**Comment by subinataws** [comment]
@larstobi - Thanks for submitting the feature request. Cache settings are enabled at the CodeBuild project level. The CodeBuild-local is mostly a helper for running and debugging buildspec.yml locally. Since the CodeBuild-local already operates on an implicit warm node, the previously downloaded source code and the Docker images are available in the volumes that are mounted. There is no plan to add support for local cache in local builds, which deviates from how it is handled in CodeBuild on AWS Cloud.

**Comment by larstobi** [comment]
Thanks for your reply!

It's actually to help debug a caching issue with my buildspec.yml locally that I would like this, so that I don't have to debug the caching issue on AWS Cloud. Which is exactly the use case you just mentioned that this is made for.

I'm not getting the Local Cache on AWS Cloud to work for me, which was why I wanted to try it with local_builds.

I've not come across any kind of warm node-ness during my tests with `local_builds/codebuild_build.sh`, so I'm not sure how that should work. The only thing it can access directly is the source directory, I guess, which is of minimal help for my use case.

I think this would be a helpful feature.

**Comment by subinataws** [comment]
@larstobi - Could you please please the details on the issue that you are facing with local caching on https://forums.aws.amazon.com/forum.jspa?forumID=230. 

To clarify my earlier comment, cache setting is defined at the Project level and that isn't something we have plans to port over to work different just for CodeBuild local. Will have the team look at the specific issue you are facing though.

**Comment by larstobi** [comment]
Will do. Thanks!
