### ISSUE TITLE
-- Feature Request -- Add yq to codebuild jobs

### ISSUE THREAD

**Issue by vibhuyadav** [aws/aws-codebuild-docker-images#347]
yq is a portable command-line YAML processor

**Github Repo -**
https://github.com/mikefarah/yq

**License Details-**
MIT License

**Comment by subinataws** [comment]
Thanks for the feature request. Due to the bloated size of these polyglot images, we are going to revisit the packages that we pre-install on the managed images to a finite set, with the next version bump. Unless absolutely required, we are going to be very selective on new package additions. It is unlikely we will install yq at this time.

**Comment by pgollucci** [comment]
If you are going to have jq then you need yq. Or you favor json over yaml having had AWS just do a large swing in the last few years.

**Comment by rtomadpg** [comment]
Hi @subinataws  - please revisit as https://github.com/aws/aws-codebuild-docker-images/tree/master/al2/x86_64/standard/5.0 is used by the Codebuild-hosted Github Actions runners. The Github-hosted runners do include "yq" (and lots more tools).

**Comment by ahgittin** [comment]
For those needing a workaround, caller the docker image seems to work fine for me in a CodeBuild `buildspec.yml`; in fact it was the _only_ "installation" method [listed on the yq page](https://github.com/mikefarah/yq/#install) which worked in my build:

```
yq() {
  docker run --rm -i -v "${PWD}":/workdir mikefarah/yq "$@"
}
```
