### ISSUE TITLE
codebuild provisioning phase in me-south-1 region

### ISSUE THREAD

**Issue by ahaffar** [aws/aws-codebuild-docker-images#424]
we noticed that CodeBuild provisioning phase is extremely slow on the `me-south-1` region, unlike `us-east-1`. we are using `aws/codebuild/amazonlinux2-x86_64-standard:3.0` image in our project.

Currently, the provisioning phase is taking  *252 secs*.

any advice on this.

**Comment by subinataws** [comment]
@ahaffar - Unfortunately, the Docker images are not cached on the build fleet today for me-south-1 (unlike us-east-1). Team will refresh the cache in an upcoming rollout. In the meantime, do consider using a custom image for your build environment.

**Comment by mo-mughrabi** [comment]
Hi @subinataws It seems like the provisioning stage is taking minimum `240+Sec` in most of our implementations in `me-south-1`; Is it caused by the docker images not being cached in the data center?

**Comment by subinataws** [comment]
@mo-mughrabi - If this is with the standard images, yes, this is unfortunately due to CodeBuild provided images not being cached on the build fleet in this region. My recommendation would be to use a self-hosted custom image until CodeBuild addresses this issue. Our apologies for the sub-optimal build experience you are encountering.

**Comment by Couper4** [comment]
Same problem in `eu-south-1` region.
Is there anything I can do to reduce `PROVISIONING` times?

**Comment by subinataws** [comment]
This should be addressed now.
