### ISSUE TITLE
Failed at aws s3 sync

### ISSUE THREAD

**Issue by randyzhou0518** [aws/aws-codebuild-docker-images#447]
Same buildspec,
if nodejs: 12 is working in 4.0
if nodejs:14 is failed at aws s3 sync in 5.0
![ubunto5](https://user-images.githubusercontent.com/77594484/113806094-0be6b880-97a5-11eb-988d-af9704fae349.PNG)

**Comment by subinataws** [comment]
Note that the 5.0 image uses AWS cli V2, while 4.0 was using AWS cli v1. This is likely due to one of the known breaking changes published in https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-s3-regional-endpoint. We'd suggest troubleshooting the build command with AWS cli V2 and updating your buildspec accordingly.
