### ISSUE TITLE
SpringBoot Error in aws/codebuild/standard:2.0

### ISSUE THREAD

**Issue by imsoncod** [aws/aws-codebuild-docker-images#454]
Spring Boot Application built on aws/codebuild/standard:2.0(ubuntu/standard/2.0) does not run since recent update.
I keep getting the'UnsatisfiedDependencyException' error.
Is the problem caused by the change of 'ubuntu/standard/2.0' to an unsupported image? So, can't I use the old version?
Application Spec : Spring Boot 2.1.0, openjdk8
thank you.

**Comment by subinataws** [comment]
@imsoncod - Thanks for reaching out. We no longer provide updates for aws/codebuild/standard:2.0, so it is marked unsupported. From your description, it is unlikely to be related to an image being marked as unsupported by CodeBuild. You can continue to use these unsupported versions, as CodeBuild won't delete them. They merely stop being cached on the build instances, which means the image pull will happen inline with the build, leading to non-trivial provisioning overhead. Due to the large image size, this can be up to 5 mins for each build.

If it is a Spring Boot specific question, I would suggest trying stackoverflow for guidance. If you believe this is related to AWS CodeBuild, do provide your buildspec and additional context on the errors.

**Comment by imsoncod** [comment]
@subinataws Thank for the reply 😀
