### ISSUE TITLE
ubuntu v4  does not include docker runtimes

### ISSUE THREAD

**Issue by rahulbreezo** [aws/aws-codebuild-docker-images#511]
**Describe the bug**
ubuntu v5 for codebuild does not include docker runtimes

**To Reproduce**
install docker 20 in runtime of codebuild v5 image

**Expected behavior**
it should get installed without any error

**Actual behaviour**
Code build throws error that says docker is not available in runtime of v5,

That actually true.  docker is not included in `runtimes.yaml` of v5.

Runtimes.yaml ref: https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/5.0/runtimes.yml

but why its not added ? someone forgot to include it ? or there is an alternative way to use docker now?

Installing docker like this in codeuild:
```
phases:
  install:
    runtime-versions:
      docker: 20
    commands:

```

**Comment by jashanbhullar** [comment]
The code for installing docker is here:
https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/5.0/Dockerfile#L401-L426

**Comment by subinataws** [comment]
@rahulbreezo - For accessing docker within a build container, you only need to set the privileged mode to true on the CodeBuild project (createProject or updateProject API calls) or override to set this flag with the startBuild API call. You should not specify docker in runtime-versions, because we no longer support specifying that in the buildspec.yml for latest version of the images.
