### ISSUE TITLE
Missing Go 1.17 after updating aws/codebuild/standard

### ISSUE THREAD

**Issue by friimaind** [aws/aws-codebuild-docker-images#552]
After the closing of these issues:

* https://github.com/aws/aws-codebuild-docker-images/issues/518
* ttps://github.com/aws/aws-codebuild-docker-images/issues/542
* ttps://github.com/aws/aws-codebuild-docker-images/issues/543

I noticed the new runtime table of Go https://docs.aws.amazon.com/codebuild/latest/userguide/runtime-versions.html and the missing 1.17 version.

We now able to use all of these versions:

```
1.12 
1.13
1.14
1.15
1.16
1.18
```

but not the 1.17.

is there a reason for this?

Thank you

**Comment by subinataws** [comment]
When CodeBuild image versions are updated, we typically pick up the latest LTS version of the runtimes. Since, Go 1.18 was available, CodeBuild went with that and skipped 1.17. CodeBuild won't have each version, but will instead look to provide the most up to date version as early as it can in its managed Docker images.
