### ISSUE TITLE
CodeBuild Docker Image to Build .IPA

### ISSUE THREAD

**Issue by andreprawira** [aws/aws-codebuild-docker-images#570]
At the moment, there is no AWS CodeBuild image that can be used to create an iOS app (.IPA), I'm requesting AWS team to create an image for that. Yes, i know this [docs](https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/build-and-test-ios-apps-with-aws-codecommit-aws-codepipeline-and-aws-device-farm.html) mentions creating iOS app in AWS but it is **using Jenkins, not Codebuild** we need an AWS native tools and image to build iOS app

Just an FYI, you can do this in Azure DevOps, they have a MacOS agent, i cant believe AWS doesnt have this feature in 2022, and yes I have talked to AWS support engineer about it and they acknowledge this issue and do not have a roadmap when they will have this feature

**Comment by subinataws** [comment]
AWS CodeBuild team member here. We unfortunately don't have a timeline for when Mac builds would be supported in CodeBuild service. We maintain this repository for sharing the Docker images used in CodeBuild. I'll resolve this issue, since it is a feature ask for AWS CodeBuild service, which is already on the team's internal backlog for consideration.
