### ISSUE TITLE
Feature request: Add  support for python 3.10 in ARM codebuild docker images

### ISSUE THREAD

**Issue by admin-zh** [aws/aws-codebuild-docker-images#628]
**Describe the bug**
Current ARM codebuild docker images(amazonlinux2-aarch64-standard:2.0 and amazonlinux2-aarch64-standard:3.0) are having gap in python env, in version 2.0 it support 3.7/3.8/3.9 and version 3.0 it supports 3.11. Why there is no 3.10?
Also, recently AWS Lambda added support for python 3.10, it makes sense to add it as supported environment too.

**Comment by subinataws** [comment]
We have another open thread around this: https://github.com/aws/aws-codebuild-docker-images/issues/608. Let's track this ask there. CodeBuild has only been supporting one language runtime image on the latest image versions. This is due to a few sharp edges that customers run into when bundling more than one version of any specific runtime. Once we have addressed that issue, we may restart offering that or provide single image runtimes to properly support the coverage of runtimes that Lambda or other AWS service offers.
