### ISSUE TITLE
is there a public accesible repository for these images?

### ISSUE THREAD

**Issue by jfromaniello** [aws/aws-codebuild-docker-images#92]
I wonder if I can build my image using something like 

```
FROM aws/codebuild/eb-nodejs-4.4.6-amazonlinux-64:2.1.3
```

Thank you very much

**Comment by clareliguori** [comment]
No, these images are not available on any public Docker registry.

**Comment by jfromaniello** [comment]
thank you

**Comment by vibhuyadav** [comment]
@clareliguori Was there a reason for this? If they are publicly available to build from the Dockerfiles in this Github repo, why aren't the images publically available to download? You are entitled to keep the answer with a No but I was just being curious.

**Comment by johnhanks1** [comment]
This is due to Ubuntu licensing.

**Comment by subinataws** [comment]
@vibhuyadav - The AL images that we have listed on the APIs are versioned locked to specific Elastic Beanstalk runtime. That's why it is not listed in this repo.

If your question was more on why don't we just distribute image on DockerHub and why only the image's Dockerfile made public, then the reason is that CodeBuild images are hosted in Amazon ECR and are not distributed on DockerHub registry.

We have plans to support CodeBuild images on AL2, at which time we should have the images on DockerHub. Hope that answers.

**Comment by vibhuyadav** [comment]
Thanks for update @subinataws Yeah that was exactly what I was looking for. I am building my own custom images now and uploading it to ECR in our own Codebuild pipeline in order to server existing CodeBuild projects.
